### ISSUE TITLE
Crash if one of the body is empty

### ISSUE THREAD

**Issue by MrChoclate** [murdho/rack-cargo#8]
If one of the response is a 204 with an empty body (`head :no_content`)
I got JSON::ParserError: A JSON text must at least contain two octets! (Most recent call first)

A possible fix could be:
```
module Rack
  module Cargo
    module ResponseBuilder
      class << self
        def response_body(app_response_body)
          response_string = ""
          app_response_body.each { |piece| response_string += piece }

          if response_string.blank?
            '' # Fix parse error if response is empty (e.g. 204)
          else
            JSON.parse(response_string)
          end
        end
      end
    end
  end
end
```

**Comment by murdho** [comment]
Thanks for letting me know, @MrChoclate! 🎉
I have added a fix to `master`. I will make a release and push the new version to RubyGems as well.
